version: "3.9"
services:
   db:
     image: postgres
     volumes:
       - .\postgresql\data:/var/lib/postgresql/data
     ports:
       - "5432:5432"
     restart: always
     container_name: postgresql
     environment:
      POSTGRES_PASSWORD: livro
      POSTGRES_USER: livro
      POSTGRES_DB: livro

   jenkins:
     depends_on:
       - db
     image: jenkins/jenkins:lts     
     privileged: true
     user: root     
     ports:
       - "8080:8080"
       - "50000:50000"
     container_name: jenkins
     volumes:
       - .\jenkins\data:/var/jenkins_home
     restart: always

   db-gogs:
     image: postgres
     volumes:
       - .\gogs\postgresql\data:/var/lib/postgresql/data
     ports:
       - "5432:5432"
     restart: always
     container_name: postgresql-gogs
     environment:
      POSTGRES_PASSWORD: gogs
      POSTGRES_USER: gogs
      POSTGRES_DB: gogs

   gogs:
#     depends_on:
#       - db-gogs
     image: gogs/gogs
     volumes:
       - .\gogs\data:/data
#       - c:\Windows\System32\Drivers\etc\hosts:/etc/hosts
     ports:
       - "10022:22"
       - "10080:3000"
     restart: always
     container_name: gogs